const categories = {
  'All Departments': 'aps',
  'Alexa Skills': 'alexa-skills',
  'Amazon Devices': 'amazon-devices',
  'Amazon Explore': 'live-explorations',
  'Amazon Fresh': 'amazonfresh',
  'Amazon Pharmacy': 'amazon-pharmacy',
  'Amazon Warehouse': 'warehouse-deals', 
  'Appliances': 'appliances', 
  'Apps Games': 'mobile-apps', 
  'Arts & Crafts Sewing': 'arts-crafts', 
  'Audible Books Originals': 'audible', 
  'Automotive Parts Accessories': 'automotive', 
  'AWS Courses': 'courses', 
  'Baby': 'baby-products', 
  'Beauty Personal Care': 'beauty', 
  'Books': 'stripbooks', 
  'CDs Vinyl': 'popular', 
  'Cell Phones Accessories': 'mobile', 
  'Clothing:  Shoes Jewelry': 'fashion', 
  'Fashion Women': 'fashion-womens', 
  'Fashion Men': 'fashion-mens', 
  'Fashion Girls': 'fashion-girls', 
  'Fashion Boys': 'fashion-boys', 
  'Fashion Baby': 'fashion-baby', 
  'Collectibles Fine Art': 'collectibles', 
  'Computers': 'computers', 
  'Credit and Payment Cards': 'financial', 
  'Digital Educational Resources': 'edu-alt-content', 
  'Digital Music': 'digital-music', 
  'Electronics': 'electronics', 
  'Garden Outdoor': 'lawngarden', 
  'Gift Cards': 'gift-cards', 
  'Grocery Gourmet Food': 'grocery', 
  'Handmade': 'handmade', 
  'Health:  Household Baby Care': 'hpc', 
  'Home Business Services': 'local-services', 
  'Home Kitchen': 'garden', 
  'Industrial Scientific': 'industrial', 
  'Just for Prime': 'prime-exclusive', 
  'Kindle Store': 'digital-text', 
  'Luggage Travel Gear': 'fashion-luggage', 
  'Luxury Stores': 'luxury', 
  'Magazine Subscriptions': 'magazines', 
  'Movies TV': 'movies-tv', 
  'Musical Instruments': 'mi', 
  'Office Products': 'office-products', 
  'Pet Supplies': 'pets', 
  'Premium Beauty': 'luxury-beauty', 
  'Prime Video': 'instant-video', 
  'Smart Home': 'smart-home', 
  'Software': 'software', 
  'Sports Outdoors': 'sporting', 
  'Subscribe Save': 'specialty-aps-sns', 
  'Subscription Boxes': 'subscribe-with-amazon', 
  'Tools Home Improvement': 'tools', 
  'Toys Games': 'toys-and-games', 
  'Under $10': 'under-ten-dollars', 
  'Video Games': 'videogames', 
  'Whole Foods Market': 'wholefoods', 
}

module.exports = categories